// GENERATED by decimal_oracle.py emit_money_parse_cast_vectors() — Ship-B P1c D-100 fixture.
// MALFORMED rows assert FLAGS ONLY (value dont-care — sites refuse; oracle stays independent).
#pragma once
#include <cstdint>
#include <cstddef>

struct MoneyParseVec { const char* s; int64_t expected; uint32_t flags; };
static const size_t MONEY_PARSE_VECTOR_COUNT = 37;
static const MoneyParseVec MONEY_PARSE_VECTORS[] = {
    { "0", 0LL, 0u },
    { "1", 100000000LL, 0u },
    { "-1", -100000000LL, 0u },
    { "+1", 100000000LL, 0u },
    { "0.0", 0LL, 0u },
    { "-0.00000000", 0LL, 0u },
    { "50000.50", 5000050000000LL, 0u },
    { "0.00006150", 6150LL, 0u },
    { "12345678.12345678", 1234567812345678LL, 0u },
    { "92233720368.54775807", 9223372036854775807LL, 0u },
    { "92233720368.54775808", 9223372036854775807LL, 2u },
    { "99999999999999.99999999", 9223372036854775807LL, 2u },
    { "-92233720368.54775807", -9223372036854775807LL, 0u },
    { "0.00000001", 1LL, 0u },
    { "-0.00000001", -1LL, 0u },
    { "70000.12345678", 7000012345678LL, 0u },
    { "3.14159265", 314159265LL, 0u },
    { "0.1", 10000000LL, 0u },
    { "0.2", 20000000LL, 0u },
    { "0.3", 30000000LL, 0u },
    { "0.123456789", 12345679LL, 4u },
    { "0.000000005", 0LL, 4u },
    { "0.000000015", 2LL, 4u },
    { "0.0000000049999", 0LL, 4u },
    { "-0.123456785", -12345678LL, 4u },
    { "1.000000005", 100000000LL, 4u },
    { "", 0LL, 1u },
    { "abc", 0LL, 1u },
    { "1.2.3", 0LL, 1u },
    { "1e5", 0LL, 1u },
    { "+", 0LL, 1u },
    { "-", 0LL, 1u },
    { ".", 0LL, 1u },
    { "12a3", 0LL, 1u },
    { "--1", 0LL, 1u },
    { "1..2", 0LL, 1u },
    { "123456789012345678901234.5", 9223372036854775807LL, 2u },
};
