// Copyright (c) 2026 Jennifer Lewis. All rights reserved.
// Licensed under the GNU Affero General Public License v3.0 (AGPL-3.0).
// See LICENSE file in the project root for full license text.
//
// DOGFOOD FIXTURE (E.1.2.A phase 3) — real unit, copied + converted, NEVER compiled.
// Source: CoreFrameworks/ExecutionCore.hpp:1-186 @ engine d4812de (2026-07-15 copy).
// Shapes exercised: BIG TEMPLATED STRUCT with access-tier bands (survey B gap #12) ·
// tier-2 [REGION] fact-scoping on real cache-line regions (D-309 #1 / D-340) · real
// assert guards via [ASSERT] (survey B gap #13) · operator-voice EDIT comment kept in place.
//
// REFINEMENT-A DROPS (stale DERIVED-class facts DROPPED, never relocated — D-342; each
// enumerated so the lossless accounting is honest):
//   1. "New layout: 2 byte flags + 6 pad + 24 (live_tp) + 24 (live_sl) + 8 pad = 64B" —
//      present-tense byte math sized for the pre-Ship-B 24B Money (Money is 16B since
//      .E.0.9); the byte-map is TOOL-OWNED now ([DIAGRAM]/[DERIVED]).
//   2. per-field "// 24B at offset 8/32 — fits in line 0" offset claims — same staleness;
//      intent ("fits in line 0", Finding A) preserved, numbers dropped.
//   HISTORICAL narrative ("Pre-v5.11.1.5 layout had live_sl spanning offsets 56-80 ...
//   due to Money=24B sizing") is KEPT verbatim — it correctly describes the OLD state
//   (history, not a stale present claim).
// All other prose relocated or kept VERBATIM; code lines byte-verbatim.

//======================================================================
// [STRUCT]_[ExecutionCore]
//----------------------------------------------------------------------
// [TAG]_[[HOT_PATH] [DATA_ORIENTED_DESIGN] [CONCURRENCY]]
// [SCOPE]_[CORE]
// [THREAD]_[[HOT_WRITER] [SLOW_READER]]
// [SYNC]_[SEQ_LOCK]
// [SYNC]_[SPSC]
// [SCHEMA]_[v1.0]
// [OVERVIEW]_[per-core trading state machine — one instance per pinned CPU core; hot path reads line 0 + permission line only in steady state]
// [REGION]_[line 0 steady-state hot reads]_[0..63]
// [THREAD]_[[HOT_WRITER]]
// [REGION]_[entry + leg-B cold fields]_[64..127]
// [REGION]_[permission — cross-thread isolate]_[128..191]
// [THREAD]_[[SLOW_WRITER] [HOT_READER]]
// [SYNC]_[ATOMIC]
//   (region byte-ranges are fixture placeholders — tool-verified at real conversion;
//    a [REGION] scopes the [THREAD]/[SYNC] lines that follow it — D-309 #1 / D-340 tier-2.
//    NOTE the ladder: [DIAGRAM] opens a freeform body, so structured region lines sit ABOVE it)
// [DIAGRAM]
//   (byte-map TOOL-OWNED — regenerated by the cache-gate --fix at real conversion;
//    fixture placeholder, do not copy values)
//   line0: [active:1][active_b:1][pad:6][live_tp:16][live_sl:16][pad] = 64B
//======================================================================
// [CODE]
//======================================================================

#pragma once

#include "../FixedPoint/FixedPointN.hpp"
#include "NodeLatencyStats.hpp"
#include "GateParameters.hpp"
#include "ParameterSlot.hpp"
#include "SPSCRing.hpp"
#include "Tick.hpp"
#include "TradeEvent.hpp"

#include <cstdint>
#include <type_traits>  // v5.11.0.E — static_assert(!std::is_polymorphic<...>)

namespace tt {

// Sized for the i5-1035G4 microbenchmark. Production sizing tuned per use case.
//
// EDIT[FROM OPERATOR]: 7-05-2026
// we could probably make this defined at the build time, using the build.sh
// script, just an idea, but it allows for different sizing easier, we could
// ideally do this for anything thats set as a constexpr across the code base
// where we set defintions, especially considering weve moved on from the i5
// processor, back to an i7, just A THOUGHT,(like me)
constexpr size_t EXECUTION_NODE_TICK_RING_SIZE  = 4096;
constexpr size_t EXECUTION_NODE_EVENT_RING_SIZE = 1024;

template <unsigned F>
struct alignas(64) ExecutionCore {
    //------------------------------------------------------------------
    // [SECTION]_[CACHE LINE 0 — steady-state HOT READS only]
    //------------------------------------------------------------------
    uint8_t  active;           // hot read: core writes and reads
    uint8_t  active_b;         // hot read: 0 in steady state when leg B inactive
    uint8_t  _pad_hot[6];
    Money   live_tp;          // hot read: steady CMOV reads every tick — line-0 resident
    Money   live_sl;          // hot read: line-0 resident (Finding A)
    uint8_t  _pad_line0[8];    // pad cache line 0 to 64

    //------------------------------------------------------------------
    // [SECTION]_[CACHE LINE 1+ — cold in steady state; only entry/leg-B paths touch]
    //------------------------------------------------------------------
    // entry_price is WRITE-only on entry events (not read in steady CMOV).
    // leg-B fields gated by `if (__builtin_expect(active_b, 0))` — line never
    // touched when leg B is inactive (steady-state default cfg).
    Money   entry_price;      // write-on-entry only; cold in steady state
    Money   entry_price_b;
    Money   live_tp_b;
    Money   live_sl_b;

    //------------------------------------------------------------------
    // [SECTION]_[permission — isolated to its OWN cache line (audit Part 1.5)]
    //------------------------------------------------------------------
    // Controller atomic-stores `permission` from a different CPU than the
    // hot path's read. Pre-v5.11.1.5: permission shared cache line 0 with
    // active/entry_price/live_tp/live_sl → controller writes invalidated the
    // line, causing ~30-50ns reload stall on the next hot-path tick.
    // Post-v5.11.1.5: permission alone on its own 64B line → controller
    // writes don't invalidate the hot-fields line.
    alignas(64) uint8_t permission;
    uint8_t  _pad_perm[63];

    //------------------------------------------------------------------
    // [SECTION]_[controller-pushed parameters + cached snapshot]
    //------------------------------------------------------------------
    // --- Parameter pack pushed by controller (phase 05) ---
    // Seqlock atomic slot. The controller calls ExecutionCore_SetParameters
    // (or ParameterSlot_Write) on its slow path; the hot path reads via
    // ParameterSlot_Read. The seqlock guarantees the consumer never reads
    // a torn value even if the producer writes back-to-back. See ParameterSlot.hpp
    // for the protocol details.
    ParameterSlot<GateParameters<F>> param_slot;

    // --- Cached parameter snapshot (phase 14 perf optimization) ---
    // The hot path skips the 192-byte memcpy of the parameter pack on every
    // tick by caching the last-read snapshot here. On each tick we do one
    // acquire-load of param_slot.seq and compare against cached_seq. If
    // they match (and cached_seq is even = "stable"), the cached_params are
    // still current and we use them directly. If they differ, we fall through
    // to the full ParameterSlot_Read to refresh the cache.
    //
    // Steady state: 1 acquire-load + 1 compare = ~1 ns
    // Param push:   1 full slot read = ~6 ns (one-time per push)
    //
    // Saves ~12 ns per tick vs the unconditional memcpy. Validated by
    // bench_batch_floor.cpp: cached_v2 ~35 ns vs original ~50 ns at the
    // batch floor. Single-writer (this core's hot path) so no atomics needed
    // on the cache fields themselves — they're only read by this core.
    uint64_t cached_seq;
    GateParameters<F> cached_params;
    // v5.12.1.B.3 — paired with cached_params; refreshed every time
    // ParameterSlot_Read fires (cached_seq miss). Used by hot-path
    // staleness gate: gap = tick.sequence - cached_publish_tick.
    // Single-writer (this core's hot path); no atomic needed.
    uint64_t cached_publish_tick;

    //------------------------------------------------------------------
    // [SECTION]_[identity + rings + tail observability]
    //------------------------------------------------------------------
    // --- Identity ---
    uint16_t node_id;
    uint8_t  _pad1[6];

    // --- Communication rings ---
    // Event ring: this core's outbound trade events. The controller is the consumer.
    SPSCRing<TradeEvent<F>, EXECUTION_NODE_EVENT_RING_SIZE> event_ring;

    // Tick ring: this core's inbound tick stream. The market reader is the producer.
    // Pointer (not embedded) because the ring is owned by the market reader, which
    // creates one per execution core at startup.
    SPSCRing<Tick<F>, EXECUTION_NODE_TICK_RING_SIZE>* tick_ring;

    // --- Latency monitoring (Phase 13 / per-core observability) ---
    // Lives at the tail of the struct so it doesn't pollute the hot fields
    // in cache line 0. Single writer (this core's hot path), single reader
    // (the controller's snapshot helper). Disabled by default; flip the
    // enable flag from the controller to start sampling.
    NodeLatencyStats latency_stats;

    // --- v5.11.0.1: Hot-path failure counters (no I/O on hot path) ---
    // Replaces inline fprintf on the rare ring-push-failure branch
    // (cascading libc-mutex stall risk under degraded conditions).
    // Single writer (this core's hot path), relaxed-load by slow path
    // for surfacing via TUISnapshot. No false sharing — accessed only
    // by this core's threads. Position at struct tail keeps the cold
    // failure-path cache line out of line 0.
    // See plans/2026-05-06-hot-path-discipline.md Rule 2 for the pattern.
    uint64_t ring_push_failures;
};

//======================================================================
// [END_CODE]
//======================================================================
// [COMMENT]_[unit model]
//----------------------------------------------------------------------
// Per-core trading state machine for the per-core risk-sharded engine.
//
// One ExecutionCore<F> instance per pinned CPU core. Each instance owns:
//   - permission   (1 bit)   — controller-granted authorization to take new entries
//   - active       (1 bit)   — currently in a trade
//   - entry_price  (Money)  — price of the current trade entry, used by SG check
//   - gate_params  (struct)  — buy/sell gate parameter pack pushed by controller
//   - event_ring   (SPSC)    — outgoing trade events the controller drains on its slow path
//   - tick_ring*   (SPSC*)   — incoming tick stream from the market reader
//
// The execution core has NO concept of a position. No P&L. No balance. No portfolio.
// All of those live on the controller core, which learns about trades by reading
// the event ring and updates the canonical Position records on its own schedule.
//======================================================================
// [COMMENT]_[per-tick algorithm]
//----------------------------------------------------------------------
// Per tick (target ~60ns flat on i5-1035G4 hardware, validated by phase 03 bench):
//   1. Compute BG_Evaluate AND SG_Evaluate unconditionally (CPU pipelines them
//      in parallel; no branch on active state).
//   2. Mask the results: can_enter = !active & permission & bg_fires
//                        can_exit  = active & sg_fires
//   3. If either fires, push a trade event to the event ring (rare branch,
//      predictable, almost always not-taken in steady state).
//   4. Update entry_price (CMOV) and active flag (mask op) branchlessly.
//
// The hot path is ALMOST entirely branchless. The only branch is the event push,
// which fires < 1% of ticks in normal operation and predicts perfectly. The gate
// evaluation, the state masks, and the active flag update are all branchless.
//
// To make it fully branchless: write the event slot fields unconditionally, then
// conditionally advance the ring head with `head += (can_enter | can_exit)`.
// This is what the phase 03 benchmark harness scenarios do for comparison.
// The production ExecutionCore uses SPSCRing_TryPush for correctness (overflow
// handling) and accepts the rare branch.
//======================================================================
// [COMMENT]_[layout history]
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// [[2026-05] [v5.11.1.5]]
//----------------------------------------------------------------------
// v5.11.1.5 layout reorder: the per-tick CMOV at hot path lines ~287-288
// reads `live_tp` + `live_sl` every tick. Pre-v5.11.1.5 layout had
// `live_sl` spanning offsets 56-80 (cache line 0 → 1) due to Money=24B
// sizing — every tick loaded 2 cache lines instead of 1.
//
// entry_price MOVED to line 1 (write-only on entry events; not in steady
// CMOV). leg-B fields gated by `if (active_b)` → line never touched in
// steady state when leg B is inactive (the common case).
//
// Audit: LATENCY_OPTIMIZATION_AUDIT.md Part 1.5 (permission isolation)
//      + plans/2026-05-06-latency-path-discipline.md Rule 1 (Finding A)
// [SUPPORTING_DOCS]
//   - [AUDIT]_[latency-optimization-part-1.5-permission-isolation]
//   - [INVARIANT]_[H6]
//======================================================================
// [DERIVED]   (tool-refreshed — do NOT hand-edit; fixture placeholders)
//----------------------------------------------------------------------
// [SIZE]_[fixture placeholder — cache-gate --fix writes the real value]
// [ALIGN]_[64]
//======================================================================
// [END_STRUCT]_[ExecutionCore]
//======================================================================

// [ASSERT]_[LAYOUT_LOCK]_[!std::is_polymorphic<ExecutionCore<64>>::value]
// [WHY]_[v5.11.0.E Part 3 architectural invariant — virtual functions introduce vtable lookups + indirect jumps that bypass the CPU branch predictor, causing pipeline stalls on hot path; a future PR adding a virtual function fails at compile]
static_assert(!std::is_polymorphic<ExecutionCore<64>>::value,
              "ExecutionCore must remain non-polymorphic — Part 3 invariant");

// [ASSERT]_[LAYOUT_LOCK]_[offsetof(live_sl) + sizeof(Money) <= 64]
// [WHY]_[v5.11.1.5 cache layout invariant — future field reorders must preserve the hot-path single-cache-line load; see latency-path-discipline Rule 1]
static_assert(offsetof(ExecutionCore<64>, live_sl) + sizeof(Money) <= 64,
              "live_sl must fit entirely in cache line 0 — see latency-path-discipline.md Rule 1");

// [ASSERT]_[LAYOUT_LOCK]_[offsetof(permission) % 64 == 0]
// [WHY]_[permission must stay cache-line-aligned to prevent false sharing — audit Part 1.5]
static_assert((offsetof(ExecutionCore<64>, permission) % 64) == 0,
              "permission must be cache-line-aligned to prevent false sharing — audit Part 1.5");

} // namespace tt
// (fixture slice ends here — ExecutionCore_Init + the tick kernel live in the real file)
